# The name of the project.
name: mern-typescript-starter
# The region where the project is deployed. Available regions: us-east-1, eu-central-1
region: us-east-1
# The version of the Genezio YAML configuration to parse.
yamlVersion: 2
backend:
  # The root directory of the backend.
  path: server
  # Information about the backend's programming language.
  language:
    # The name of the programming language.
    name: js
    # The package manager used by the backend.
    packageManager: npm
  # Information about the backend's functions.
  functions:
    # The name (label) of the function.
    - name: mern-typescript-starter
      # The path to the function's code.
      path: ./
      # The name of the function handler
      handler: handler
      # The entry point for the function.
      entry: dist/app.js
      # The compatibility of the function handler.
      type: httpServer
  # Scripts are running in the specified `path` directory.
  scripts:
    # List of scripts to run before deploying the frontend.
    deploy: 
      - npm install
      - npm run build
    # List of scripts that build your frontend before deployment. It should populate the specified `publish` directory.
    local: 
      - npm install
      - npm run build
# Information about the backend's services.
services:
  # The name of the service.
  databases:
    # The name of the database.
    - name: my-mongo-db
      # The region where the database is deployed.
      region: us-east-1
      type: mongo-atlas
frontend:
  # The folder where the frontend scripts will run.
  path: client
  # Specifies information about the SDK generation. If not specified, the SDK will not be generated for this frontend.
  # The directory that will be published to the CDN. It is relative to the `path` directory.
  publish: ./dist
  # Environment variables that will be injected into the frontend.
  scripts:
    # List of scripts to run before deploying the frontend.
    deploy: npm install
    build: npm run build
    start: 
      - npm install
      - npm run dev
  environment:
    VITE_API_URL: ${{ backend.functions.mern-typescript-starter.url }}
